### ISSUE TITLE
PNG image in the item

### ISSUE THREAD

**Issue by robertotucci** [Collaborne/paper-collapse-item#1]
Hi,
I inserted a new feature in the file paper-collapse-item.html but i'm not enable to push my code.
I think that could be very useful insert an image instead of an icon in the item...
I changed your code as is:

`<iron-icon class='icon' src="[[src]]" icon=[[icon]]></iron-icon>`

```
Polymer({
        is: 'paper-collapse-item',
        properties: {
            header: String,
            icon: String,
            src: String,
```

Can you insert this feature in your code please?
Thanks!

**Comment by ronnyroeller** [comment]
@robertotucci - Thanks for the suggestion! Feel free to provide a PR.

**Comment by ronnyroeller** [comment]
PR has been merged and new release is created. Thanks for the contribution!
