### ISSUE TITLE
Toggle already opened collapse when opening another

### ISSUE THREAD

**Issue by JurgenKnops** [Collaborne/paper-collapse-item#12]
Hi,

Wrapping up two or more `paper-collapse-item` elements in a div; is there a way to trigger/toggle (to close) an already opened collapse when opening another one? For now it's acting like a multi collapse.

**Comment by ronnyroeller** [comment]
Introducing something like a `paper-collapse-item-group` sounds like a good idea. Feel free to provide a PR.

**Comment by hyyan** [comment]
@JurgenKnops  @ronnyroeller  what about this  : 


``` html
<paper-collapse-item id="collapse1" icon="editor:mode-comment"  on-toggle="onToggleListener">
</paper-collapse-item>
<paper-collapse-item id="collapse2" icon="editor:mode-comment"  on-toggle="onToggleListener">
</paper-collapse-item>
<paper-collapse-item id="collapse3" icon="editor:mode-comment"  on-toggle="onToggleListener">
</paper-collapse-item>
```

``` js
 var items = this.querySelectorAll("paper-collapse-item");
    for(var x=0;x<items.length;x++){
      if(items[x].id !== e.detail.id){
          items[x].opened = false;
      }
  }
```

**Comment by hyyan** [comment]
@ronnyroeller This issue is resolved

**Comment by hyyan** [comment]
@ronnyroeller still an issue ?

**Comment by ronnyroeller** [comment]
Resolved indeed

**Comment by davie-robertson** [comment]
it seems that this paper-collapse-group doesn't work if it's nested within an existing paper-collapse-item (when I have levels of content within other levels of content)
