### ISSUE TITLE
Impossible to remove left- and right-padding on content.

### ISSUE THREAD

**Issue by paulcuth** [Collaborne/paper-collapse-item#15]
Hi,

Thank you for sharing this component, it's very useful. 
However, I find myself needing collapsable content that is the same width as the host element and I can't find a way to achieve this. `paper-collapse-item` uses `paper-item`s which have left- and right-padding of `16px` and it looks like there's no access to the styling of those elements, so I can't remove the padding.
If you could expose the style of these, it would be much appreciated.

Paul.

**Comment by ronnyroeller** [comment]
@paulcuth - Thanks for your feedback. Indeed, the element is opinionated about the Material Design spec (which advises on these paddings in most cases).
But I clearly understand your use case. Feel free to provide a PR that introduces a mixin to overwrite the default. Happy to merge in.

**Comment by lauritowal** [comment]
Is there a solution already? I've tried 
```
            paper-collapse-item {
                --paper-item: {
                    padding: 0;
                };
}
```
But this somehow affects other elements outside of paper-collapse-item too. @paulcuth @ronnyroeller

**Comment by laurentpellegrino** [comment]
Same issue here.

**Comment by Enrique199413** [comment]
Please check the https://github.com/Collaborne/paper-collapse-item/pull/27 and I was update the documentation :+1: @Collaborne

**Comment by ankon** [comment]
Closing: You can modify the styling of the simple-paper-item thanks to #27, which should provide a solution for this issue. Thanks!
