### ISSUE TITLE
Polymer 2

### ISSUE THREAD

**Issue by hyyan** [Collaborne/paper-collapse-item#16]
The element is not ready yet to be used with Polymer 2, is there a plan?

**Comment by ronnyroeller** [comment]
I'll start migrating once there is a stable release of Polymer 2.

**Comment by hyyan** [comment]
@ronnyroeller Awesome, just raise a hand if you want help  :), Ah and  maybe we can use this issue to document what is needed to upgrade to Polymer 2

Cheers 🍺

**Comment by ronnyroeller** [comment]
@hyyan The element is ready for Polymer 2 :fireworks:

**Comment by hyyan** [comment]
Thanks for the update,  Great Job!

Am 19.06.2017 17:23 schrieb "Ronny Roeller" <notifications@github.com>:
