### ISSUE TITLE
Add align-items style to the header class

### ISSUE THREAD

**Issue by dannywolfmx** [Collaborne/paper-collapse-item#28]
I think the content of the header will look better if an @apply --layout-center is added; to align the content

this is without @apply --layout-center
![screenshot_6](https://user-images.githubusercontent.com/1672871/39379727-d0a0647a-4a21-11e8-9bc4-dcac02bb2e90.png)

And this is with the fix
![screenshot_5](https://user-images.githubusercontent.com/1672871/39379732-d5103850-4a21-11e8-9ac6-943f186a4757.png)

**Comment by ankon** [comment]
I couldn't find any explicit spec on the alignment, but that might just be me being bad at searching. 

Looking at the examples in https://material.io/guidelines/components/expansion-panels.html#expansion-panels-behavior and https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-menu-controls it seems indeed that the chevron should be aligned as you propose.
