### ISSUE TITLE
Will there be a Polymer 3 version of this component?

### ISSUE THREAD

**Issue by binbalenci** [Collaborne/paper-collapse-item#29]

**Comment by davidmaxwaterman** [comment]
Is there a Polymer 2 version?
That isn't shown on here:
https://www.webcomponents.org/element/Collaborne/paper-collapse-item

 other elements seem to have a 'polymer 2 supported' badge:
https://camo.githubusercontent.com/4aa0630e342a936fab45df12d0294d6b877a3706/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506f6c796d6572322d737570706f727465642d626c75652e737667

**Comment by binbalenci** [comment]
@davidmaxwaterman It clearly says
```
Dependencies: polymer^2.0.0
```

**Comment by davidmaxwaterman** [comment]
oh yes, so it does...thanks. As I mentioned, others seem to have that badge, though I can't find it now on any of them. It seems there is some inconsistency in the badging...but anyway, I'll look down in the dependencies from now on.

**Comment by binbalenci** [comment]
@davidmaxwaterman Don't rely too much on the badge 😉 Another quick way is to check the `bower.json` or `package.json`, at least that's how I do it.

**Comment by hyyan** [comment]
@binhbbbb The element can be converted to polymer 3 style using [polymer-modulizer](https://github.com/Polymer/polymer-modulizer) , if you have some time a PR will be appreciated.
Unfortunately I do not have time to help with this now , but I'll try to do it at the weekend if no one did it

**Comment by ronnyroeller** [comment]
Guys, we don't have a fixed schedule when we will migrate to Polymer 3 (turns out that this is a bit more difficult than it looks in the Google IO videos ;)
But sure, we'd merge a PR if anybody want to look into this.

**Comment by hyyan** [comment]
@binhbbbb ,@davidmaxwaterman , @ronnyroeller 
I have sent a [PR](https://github.com/Collaborne/paper-collapse-item/pull/31)  which fixes this issue
I hope it will be merged soon.

**Comment by ronnyroeller** [comment]
Closed with https://github.com/Collaborne/paper-collapse-item/pull/31
