### ISSUE TITLE
Why are you using paper-item?

### ISSUE THREAD

**Issue by atishpatel** [Collaborne/paper-collapse-item#3]
Hey, 

I was using your element and I ran across an issue where the space key wouldn't work in my paper-input. I realized it's because you are using paper-item. Is there a reason for this? If it's just to have a material design card, it should be a paper-material instead of a paper-item.

**Comment by ronnyroeller** [comment]
For compliant layouting (e.g. spacing around the item, text, etc.), which `paper-item` already implements.
